### ISSUE TITLE
Disabled Property

### ISSUE THREAD

**Issue by majew7** [maxifjaved/react-oauth2#3]
Can a new prop be introduced:
- `isDisabled`
- `disabled`

which can be forwarded to the underlying `<button>`?

**Comment by majew7** [comment]
I'd like to fix this, and contribute to this repo.  However upon: `git push -u origin disabled-property`, I receive a permission error.

```
ERROR: Permission to maxifjaved/react-oauth2.git denied to majew7.
fatal: Could not read from remote repository.
```

**Comment by maxifjaved** [comment]
Please open a pull request.

**Comment by majew7** [comment]
Sure.  https://github.com/maxifjaved/react-oauth2/pull/4
I updated the version with a minor update.

Regarding the build/distribution files, should that be in one of the commits as well?

**Comment by maxifjaved** [comment]
pull request approved.

**Comment by majew7** [comment]
Thanks @maxifjaved.

Great... Regarding the build/distribution files, should that be in one of the commits as well?  Will you take care of this?  Or have I missed something?

**Comment by majew7** [comment]
Hi @maxifjaved, The file `/build/index.js`, will you build this?  What is your intended process?
